name: Build & Test - API
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: ./.github/actions/container-build-and-test
        with:
          docker-file-path: demo/src/api
          test-path: demo/test/integration/test_integration_api.py