name: Build Source
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ros:noetic
    steps:
      - name: Install Pre-Reqs
        run: sudo apt-get install -y colcon-common-extensions colcon-lcov-result colcon-coveragepy-result colcon-mixin rosdep vcstool
      # - uses: ros-tooling/setup-ros@v0.7
      #   with:
      #     required-ros-distributions: noetic
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: demo
          target-ros1-distro: noetic