name: Build Source
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ros:noetic
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: noetic
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: my_package
          target-ros1-distro: noetic